# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'Code4SocialGood' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Code4SocialGood
  pod 'Alamofire', '4.5.1'
  pod 'SwiftyJSON', '4.0.0'
  pod 'ObjectMapper', '3.1.0'
end
